apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sequences.foo.com
spec:
  group: foo.com
  version: v1
  scope: Namespaced
  names:
    plural: sequences
    singular: sequence
    kind: Sequence
    shortNames: ["sq", "seq"]
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: sequence-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: foo.com/v1
    resource: sequences
  childResources:
    - apiVersion: v1
      resource: pods
  hooks:
    sync:
      webhook:
        url: http://10.0.2.2:5000/syncSequence # Minikube IP under virtualbox
        timeout: 20s
